#!/bin/bash
sudo systemctl disable HihPaho
sudo service HihPaho stop

mkdir -p ../bin
g++ -o ../bin/HihPaho.exe -I../include ../src/PahoInterface.cc HihPaho.cc -lcpprest -lpaho-mqtt3a -l paho-mqttpp3 -lpthread  -lgpiod -li2c

sudo mkdir -p /usr/local/paho/bin
sudo cp ../bin/HihPaho.exe /usr/local/paho/bin/
sudo sed -e 's,SERVICENAME,HihPaho,g' ../etc/example.service > HihPaho.service
sudo cp HihPaho.service /lib/systemd/system/
sudo systemctl enable HihPaho
sudo service HihPaho stop
