# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _FebWriter
else:
    import _FebWriter

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _FebWriter.delete_SwigPyIterator

    def value(self):
        return _FebWriter.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _FebWriter.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _FebWriter.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _FebWriter.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _FebWriter.SwigPyIterator_equal(self, x)

    def copy(self):
        return _FebWriter.SwigPyIterator_copy(self)

    def next(self):
        return _FebWriter.SwigPyIterator_next(self)

    def __next__(self):
        return _FebWriter.SwigPyIterator___next__(self)

    def previous(self):
        return _FebWriter.SwigPyIterator_previous(self)

    def advance(self, n):
        return _FebWriter.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _FebWriter.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _FebWriter.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _FebWriter.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _FebWriter.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _FebWriter.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _FebWriter.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _FebWriter:
_FebWriter.SwigPyIterator_swigregister(SwigPyIterator)

class UintVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _FebWriter.UintVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _FebWriter.UintVector___nonzero__(self)

    def __bool__(self):
        return _FebWriter.UintVector___bool__(self)

    def __len__(self):
        return _FebWriter.UintVector___len__(self)

    def __getslice__(self, i, j):
        return _FebWriter.UintVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _FebWriter.UintVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _FebWriter.UintVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _FebWriter.UintVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _FebWriter.UintVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _FebWriter.UintVector___setitem__(self, *args)

    def pop(self):
        return _FebWriter.UintVector_pop(self)

    def append(self, x):
        return _FebWriter.UintVector_append(self, x)

    def empty(self):
        return _FebWriter.UintVector_empty(self)

    def size(self):
        return _FebWriter.UintVector_size(self)

    def swap(self, v):
        return _FebWriter.UintVector_swap(self, v)

    def begin(self):
        return _FebWriter.UintVector_begin(self)

    def end(self):
        return _FebWriter.UintVector_end(self)

    def rbegin(self):
        return _FebWriter.UintVector_rbegin(self)

    def rend(self):
        return _FebWriter.UintVector_rend(self)

    def clear(self):
        return _FebWriter.UintVector_clear(self)

    def get_allocator(self):
        return _FebWriter.UintVector_get_allocator(self)

    def pop_back(self):
        return _FebWriter.UintVector_pop_back(self)

    def erase(self, *args):
        return _FebWriter.UintVector_erase(self, *args)

    def __init__(self, *args):
        _FebWriter.UintVector_swiginit(self, _FebWriter.new_UintVector(*args))

    def push_back(self, x):
        return _FebWriter.UintVector_push_back(self, x)

    def front(self):
        return _FebWriter.UintVector_front(self)

    def back(self):
        return _FebWriter.UintVector_back(self)

    def assign(self, n, x):
        return _FebWriter.UintVector_assign(self, n, x)

    def resize(self, *args):
        return _FebWriter.UintVector_resize(self, *args)

    def insert(self, *args):
        return _FebWriter.UintVector_insert(self, *args)

    def reserve(self, n):
        return _FebWriter.UintVector_reserve(self, n)

    def capacity(self):
        return _FebWriter.UintVector_capacity(self)
    __swig_destroy__ = _FebWriter.delete_UintVector

# Register UintVector in _FebWriter:
_FebWriter.UintVector_swigregister(UintVector)

MAX_EVENT_SIZE = _FebWriter.MAX_EVENT_SIZE
class FebWriter(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, dire, location):
        _FebWriter.FebWriter_swiginit(self, _FebWriter.new_FebWriter(dire, location))

    def newRun(self, runid, resetEventNumber=True):
        return _FebWriter.FebWriter_newRun(self, runid, resetEventNumber)

    def endRun(self):
        return _FebWriter.FebWriter_endRun(self)

    def writeRunHeader(self, header):
        return _FebWriter.FebWriter_writeRunHeader(self, header)

    def eventNumber(self):
        return _FebWriter.FebWriter_eventNumber(self)

    def runNumber(self):
        return _FebWriter.FebWriter_runNumber(self)

    def totalSize(self):
        return _FebWriter.FebWriter_totalSize(self)

    def newEvent(self):
        return _FebWriter.FebWriter_newEvent(self)

    def appendEventData(self, val):
        return _FebWriter.FebWriter_appendEventData(self, val)

    def writeEvent(self):
        return _FebWriter.FebWriter_writeEvent(self)

    def file_name(self):
        return _FebWriter.FebWriter_file_name(self)

    def useShm(self):
        return _FebWriter.FebWriter_useShm(self)

    def setShmDirectory(self, shmd):
        return _FebWriter.FebWriter_setShmDirectory(self, shmd)

    def setIds(self, did, sid):
        return _FebWriter.FebWriter_setIds(self, did, sid)
    __swig_destroy__ = _FebWriter.delete_FebWriter

# Register FebWriter in _FebWriter:
_FebWriter.FebWriter_swigregister(FebWriter)



