services:
  apache:
    image: httpd:2.4
    container_name: mon_apache
    ports:
      - 7070:80
    volumes:
      - /usr/local/pmdaq/htdocs:/usr/local/apache2/htdocs/
    restart: always
  picmic:
    build: /opt/pmdaq/picmic/services
    container_name: tkweb-picmic

    environment:
      - MGDBLOGIN=acqilc/RPC_2008@lyoilcdaq01:27017@PICMIC
      - PYTHONPATH=/usr/local/driver:/usr/local/pmdaq/share:/opt/pmdaq/picmic:/opt/pmdaq/picmic/services:/opt/pmdaq/picmic/share:/opt/pmdaq/picmic/db

    volumes:
      - /home/acqcmsmu/liroc_picotdc_daq/software/:/usr/local/driver
      - /usr/local/pmdaq/share:/usr/local/pmdaq/share
      - /usr/local/pmdaq/etc:/usr/local/pmdaq/etc	
      - /opt/pmdaq/picmic:/opt/pmdaq/picmic

    working_dir: /opt/pmdaq/picmic/services

    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

    ports:
      - "8000:8000"
    restart: unless-stopped
