#!/bin/bash
sudo systemctl disable WienerPaho.service 
sudo service WienerPaho stop

g++ -o ../bin/WienerPaho.exe -I../include ../src/PahoInterface.cc WienerSnmp.cc WienerPaho.cc -lcpprest  -lpaho-mqtt3a -lpaho-mqttpp3 -lpthread 

sudo mkdir -p /usr/local/paho/bin
sudo cp ../bin/WienerPaho.exe /usr/local/paho/bin/
sudo sed -e 's,SERVICENAME,WienerPaho,g' ../etc/example.service > WienerPaho.service
sudo cp WienerPaho.service /lib/systemd/system/
sudo systemctl enable WienerPaho.service 
sudo service WienerPaho start
